import "./globals.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="it" data-theme="fantasy">
      <body className="w-screen min-h-screen flex flex-col items-center justify-start">{children}</body>
    </html>
  );
}
